name: Node - Prebuild

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    name: 'Lint'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@646cdf48217256a3d0b80361c5a50727664284f2
        with:
          version: 6.10.0

      # Setup
      - name: Setup
        uses: actions/setup-node@v2
        with:
          check-latest: true
          cache: 'pnpm'
          cache-dependency-path: './pnpm-lock.yaml'

      # Caches
      - name: Cache eslint
        uses: actions/cache@v2
        with:
          path: ./.eslintcache
          key: ${{ runner.os }}-cache-eslint
      
      # Install
      - name: Install
        if: steps.cache.outputs.cache-hit != 'true'
        run: pnpm install

      # Run
      - name: Lint
        run: pnpm run lint

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.1.2
        with:
          commit_message: 'style: format'
          branch: ${{ github.head_ref }}
