name: Node - Prebuild

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  typecheck:
    name: 'Typecheck'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 6.10.0

      # Setup
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          check-latest: true
          cache: 'pnpm'
          cache-dependency-path: './pnpm-lock.yaml'

      # Install
      - name: Install
        run: pnpm install
      # Run
      - name: Typecheck
        run: pnpm run typecheck

  lint:
    name: 'Lint'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 6.10.0

      # Setup
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          check-latest: true
          cache: 'pnpm'
          cache-dependency-path: './pnpm-lock.yaml'

      # Install
      - name: Install dependencies
        run: pnpm install
      # Run
      - name: Lint
        run: pnpm run lint

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.1.2
        with:
          commit_message: 'style: format'
          branch: ${{ github.head_ref }}


  test:
    needs: [lint, typecheck]
    name: 'Test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 6.10.0

      # Setup
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          check-latest: true
          cache: 'pnpm'
          cache-dependency-path: './pnpm-lock.yaml'


      # Install
      - name: Install dependencies
        run: pnpm install
      # Run
      - name: Test
        run: pnpm run test
