name: Node - Prebuild

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  typecheck:
    name: 'Typecheck'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Setup
      - name: Setup
        uses: actions/setup-node@v2
        with:
          check-latest: true
          cache: 'npm'
          cache-dependency-path: './package-lock.json'

      # Install
      - name: Install dependencies
        run: npm ci --no-audit --prefer-offline --ignore-scripts

      # Run
      - name: Typecheck
        run: npm run typecheck

  lint:
    name: 'Lint'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Setup
      - name: Setup
        uses: actions/setup-node@v2
        with:
          check-latest: true
          cache: 'npm'
          cache-dependency-path: './package-lock.json'

      # Install
      - name: Install dependencies
        run: npm ci --no-audit --prefer-offline --ignore-scripts

      # Run
      - name: Lint
        run: npm run lint

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.1.2
        with:
          commit_message: 'style: format'
          branch: ${{ github.head_ref }}


  test:
    needs: [lint, typecheck]
    name: 'Test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Setup
      - name: Setup
        uses: actions/setup-node@v2
        with:
          check-latest: true
          cache: 'npm'
          cache-dependency-path: './package-lock.json'


      # Install
      - name: Install dependencies
        run: npm ci --no-audit --prefer-offline --ignore-scripts

      # Run
      - name: Test
        run: npm run test
