name: Node - Prebuild

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  typecheck:
    name: 'Typecheck'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: technote-space/get-diff-action@v4
        with:
          PATTERNS: |
            ./src/**/*.{ts,tsx}
            **/tsconfig.json
            **/tsconfig*.json

      # Setup
      - name: Setup
        if: env.GIT_DIFF
        uses: actions/setup-node@v2
        with:
          check-latest: true
          cache: 'npm'
          cache-dependency-path: './package-lock.json'

      # Install
      - name: Install dependencies
        if: env.GIT_DIFF
        run: npm ci --no-audit -ignore-scripts --ignore-scripts

      # Run
      - name: Typecheck
        if: env.GIT_DIFF
        run: npm run typecheck

  lint:
    name: 'Lint'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: technote-space/get-diff-action@v4
        with:
          PATTERNS: |
            **/*.{js,jsx,ts,tsx,json,html}

      # Setup
      - name: Setup
        if: env.GIT_DIFF
        uses: actions/setup-node@v2
        with:
          check-latest: true
          cache: 'npm'
          cache-dependency-path: './package-lock.json'

      # Install
      - name: Install dependencies
        if: env.GIT_DIFF
        run: npm ci --no-audit -ignore-scripts

      # Run
      - name: Lint
        if: env.GIT_DIFF
        run: npm run lint

      - name: Commit changes
        if: env.GIT_DIFF
        uses: stefanzweifel/git-auto-commit-action@v4.1.2
        with:
          commit_message: 'style: format'
          branch: ${{ github.head_ref }}


  test:
    needs: [lint, typecheck]
    name: 'Test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: technote-space/get-diff-action@v4
        with:
          PATTERNS: |
            **/*.test.*
            ./src/**/*.*

      # Setup
      - name: Setup
        if: env.GIT_DIFF
        uses: actions/setup-node@v2
        with:
          check-latest: true
          cache: 'npm'
          cache-dependency-path: './package-lock.json'


      # Install
      - name: Install dependencies
        if: env.GIT_DIFF
        run: npm ci --no-audit -ignore-scripts

      # Run
      - name: Test
        if: env.GIT_DIFF
        run: npm run test
