name: Node - Publish

on:
  push:
    branches: [master]

jobs:
  typecheck:
    name: 'Typecheck'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Find Changed Files
        uses: technote-space/get-diff-action@v4
        with:
          PATTERNS: |
            src/**/*.{ts,tsx}
            **/tsconfig.json
            **/tsconfig*.json

      - name: Setup PNPM
        if: env.GIT_DIFF
        uses: pnpm/action-setup@v2
        with:
          version: 6.10.0

      - name: Setup Node
        if: env.GIT_DIFF
        uses: actions/setup-node@v2
        with:
          check-latest: true
          cache: 'pnpm'
          cache-dependency-path: './pnpm-lock.yaml'

      - name: Install
        if: env.GIT_DIFF
        run: pnpm install

      - name: Typecheck
        if: env.GIT_DIFF
        run: pnpm run typecheck

  lint:
    name: 'Lint'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Find Changed Files
        uses: technote-space/get-diff-action@v4
        with:
          PATTERNS: |
            **/*.{js,jsx,ts,tsx,json,html}

      - name: Setup PNPM
        if: env.GIT_DIFF
        uses: pnpm/action-setup@v2
        with:
          version: 6.10.0

      - name: Setup Node
        if: env.GIT_DIFF
        uses: actions/setup-node@v2
        with:
          check-latest: true
          cache: 'pnpm'
          cache-dependency-path: './pnpm-lock.yaml'

      - name: Install dependencies
        if: env.GIT_DIFF
        run: pnpm install

      - name: Lint
        if: env.GIT_DIFF
        run: pnpm run lint

      - name: Commit changes
        if: env.GIT_DIFF
        uses: stefanzweifel/git-auto-commit-action@v4.1.2
        with:
          commit_message: 'style: format'
          branch: ${{ github.head_ref }}

  test:
    name: 'Unit Tests'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Find Changed Files
        uses: technote-space/get-diff-action@v4
        with:
          PATTERNS: |
            src/**/*.test.*
            src/**/*.*

      - name: Setup PNPM
        if: env.GIT_DIFF
        uses: pnpm/action-setup@v2
        with:
          version: 6.10.0

      - name: Setup Node
        if: env.GIT_DIFF
        uses: actions/setup-node@v2
        with:
          check-latest: true
          cache: 'pnpm'
          cache-dependency-path: './pnpm-lock.yaml'

      - name: Install dependencies
        if: env.GIT_DIFF
        run: pnpm install

      - name: Test
        if: env.GIT_DIFF
        run: pnpm run test

  publish:
    needs: [lint, typecheck, test]
    name: 'Build && Publish'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Get Package Info
        id: packageInfo
        uses: codex-team/action-nodejs-package-info@v1

      - name: Check Version Difference
        id: checkVersion
        uses: EndBug/version-check@v1
        with:
          file-url: https://unpkg.com/${{ steps.packageInfo.outputs.name }}@latest/package.json
          static-checking: localIsNew

      - name: Setup PNPM
        if: steps.check.outputs.changed == 'true'
        uses: pnpm/action-setup@v2
        with:
          version: 6.10.0

      - name: Setup Node
        if: steps.check.outputs.changed == 'true'
        uses: actions/setup-node@v2
        with:
          check-latest: true
          cache: 'pnpm'
          cache-dependency-path: './pnpm-lock.yaml'

      - name: Install dependencies
        if: steps.check.outputs.changed == 'true'
        run: pnpm install

      - name: Build
        if: steps.check.outputs.changed == 'true'
        run: pnpm run build

      - name: Publish
        if: steps.check.outputs.changed == 'true'
        run: pnpm publish
