name: Node - Prebuild

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    name: 'Lint'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Setup
      - name: Setup
        uses: actions/setup-node@v2
        with:
          # check-latest: true
          node-version: 16
          cache: 'pnpm'
          cache-dependency-path: |
            '**/pnpm-lock.yaml'
            '**/.eslintcache'
      
      # Install
      - name: Install PNPM
        run: npm i -g pnpm

      - name: Install
        run: pnpm i

      # Run
      - name: Lint
        run: pnpm run lint

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.1.2
        with:
          commit_message: 'style: format'
          branch: ${{ github.head_ref }}
